-- ==============================================================================
-- Academy Management System - Feature Migrations
-- Run this script in the Supabase SQL Editor
-- ==============================================================================

-- 1. Pending Registrations Table
CREATE TABLE IF NOT EXISTS public.pending_registrations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_details JSONB NOT NULL,
    parent_details JSONB NOT NULL,
    health_details JSONB,
    payment_method TEXT,
    gdpr_consent BOOLEAN DEFAULT false,
    signature TEXT,
    status TEXT DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    admin_notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for pending_registrations
ALTER TABLE public.pending_registrations ENABLE ROW LEVEL SECURITY;

-- Allow public inserts
CREATE POLICY "Allow public inserts" ON public.pending_registrations
    FOR INSERT TO public
    WITH CHECK (true);

-- Allow authenticated users (admin) to select, update, delete
CREATE POLICY "Allow authenticated full access" ON public.pending_registrations
    FOR ALL TO authenticated
    USING (true)
    WITH CHECK (true);


-- 2. Privacy Policies Table
CREATE TABLE IF NOT EXISTS public.privacy_policies (
    id SERIAL PRIMARY KEY,
    version INTEGER NOT NULL,
    content TEXT NOT NULL,
    status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
    published_by INTEGER REFERENCES public.users(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for privacy_policies
ALTER TABLE public.privacy_policies ENABLE ROW LEVEL SECURITY;

-- Allow public to select published policies
CREATE POLICY "Allow public to read published policies" ON public.privacy_policies
    FOR SELECT TO public
    USING (status = 'published');

-- Allow authenticated users to manage policies
CREATE POLICY "Allow authenticated full access" ON public.privacy_policies
    FOR ALL TO authenticated
    USING (true)
    WITH CHECK (true);

-- 3. Modify Users Table
ALTER TABLE public.users 
ADD COLUMN IF NOT EXISTS privacy_consent_version INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS signature TEXT;

-- 4. Audit Log Helper (if not exists)
-- Assuming audit_log table exists, we just need to ensure it's there.
CREATE TABLE IF NOT EXISTS public.audit_log (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    admin_id INTEGER REFERENCES public.users(id),
    action TEXT NOT NULL,
    target_table TEXT,
    target_id TEXT,
    details TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
